### ISSUE TITLE
How can I get closer to the planet?

### ISSUE THREAD

**Issue by trsh** [J-Zeitler/chunked-lod#1]
M?

**Comment by J-Zeitler** [comment]
Sorry for not getting back to you, had to find time to try it out. It's the `alt`/`option` key + scroll (on a trackpad at least):

setting is here: https://github.com/J-Zeitler/chunked-lod/blob/6a4edd557582595524a15458bbd153d5dcc952b5/src/libs/planetControls.js#L5
